title: Pengyuan Wang's Homepage
page-top-title: Pengyuan Wang
top-section-bg-text: Practise makes perfect.
home-subtitle: Pengyuan Wang&ensp;|&ensp;firmware engineer&ensp;
copyright-text: '&copy; Pengyuan Wang 2023-2025. All Rights Reserved.'
